name: build

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number ||  github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' && github.event_name == 'push' }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@e16d53d6bd770a44251028540390e0eff801aef5 # v5.0.55
        with:
          save-cache: true

  lint:
    needs:
      - setup
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@e16d53d6bd770a44251028540390e0eff801aef5 # v5.0.55

      - name: lint
        run: |
          pnpm oxlint --format github
          pnpm oxfmt
          pnpm lint:types

      - name: Check workflow files
        uses: docker://ghcr.io/jdx/jactionlint:2.1.0@sha256:50503986432f31db3513648af62e05f0a1f88da671c972c0e9bc252731e9300d
        with:
          args: -color

  test:
    needs:
      - setup
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@e16d53d6bd770a44251028540390e0eff801aef5 # v5.0.55

      - name: test
        run: pnpm test
